[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false
enableCaching = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#F8D96D"
backgroundColor = "#10263D"
secondaryBackgroundColor = "#1a3658"
textColor = "#FFFFFF"
