[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#10263D"
backgroundColor = "#10263D"
secondaryBackgroundColor = "#1a3658"
textColor = "#FFFFFF"
font = "sans serif"

[client]
toolbarMode = "minimal"

[logger]
level = "info"
