[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#F8D96D"
backgroundColor = "#10263D"
secondaryBackgroundColor = "#1a3658"
textColor = "#FFFFFF"
